**Lesson 2**

Theme:
**Numpy**

#Tasklist:

1.  Find the target in the dataset and remove this column from the dataset (delete by index)

2.  Convert the remaining columns to a 2D array (or make sure that it is already a 2D array)

3.  Calculate mean, median, standard deviation for the 1st column

4.  Insert 20 values of np.nan at random positions in the array (using normal randomization, there may be overlapping positions, so find a solution that guarantees 20 unique positions)

5.  Find the positions of the inserted np.nan values in the 1st column

6.  Filter the array by the condition: values in the 3rd column > 1.5 and values in the 1st column < 5.0 (save to another variable)

7.  Replace all np.nan values with 0

8.  Count all unique values in the array and print them along with the number

9.  Split the array vertically into 2 equal parts (do not use absolute numbers, there should be two arrays of 4 columns each)

10.  Sort both arrays by the 1st column: 1st in ascending order, 2nd in descending order

11.  Merge both arrays into one

12.  Find the most frequently repeated value in the array

13.  Write a function that multiplies all values in a column that are less than the average value in that column by 2 and divides the remaining values by 4.

14.  Apply the resulting function to the 3rd column

In [1]:
# import necessary libraries

import pandas as pd
import numpy as np

from google.colab import drive
drive.mount('/content/gdrive/', force_remount=True)

Mounted at /content/gdrive/


In [2]:
#define path of dataset

data_path = "/content/gdrive/MyDrive/Hillel_ML_Course/data/Iris.csv"

# **Task 1**

Find the target in the dataset and remove this column from the dataset (delete by index)

##Solution with pandas and np

In [3]:
# read file as pandas df

data = pd.read_csv(data_path)
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
# removing target column by pandas

removed_target = data.drop("Species", axis=1)
removed_target.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0   1            5.1           3.5            1.4           0.2
1   2            4.9           3.0            1.4           0.2
2   3            4.7           3.2            1.3           0.2
3   4            4.6           3.1            1.5           0.2
4   5            5.0           3.6            1.4           0.2

In [5]:
#we can convert pandas+ dataframe to np

data_np = data.to_numpy().copy()

In [6]:
#removing rarget column by copying array without it

removed_target_np = data_np[:, 0:5]
removed_target_np[:5, :]

array([[1, 5.1, 3.5, 1.4, 0.2],
       [2, 4.9, 3.0, 1.4, 0.2],
       [3, 4.7, 3.2, 1.3, 0.2],
       [4, 4.6, 3.1, 1.5, 0.2],
       [5, 5.0, 3.6, 1.4, 0.2]], dtype=object)

##Task solution with numpy

In [7]:
#and we can load file directly by numpy without "target: and id "columns"

load_data_np = np.genfromtxt(data_path, dtype=float, delimiter=',', usecols=(1,2,3,4))

In [8]:
# look at the first 5 rows
load_data_np[:5,:]

array([[nan, nan, nan, nan],
       [5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2]])

In [9]:
#fist row is nan, so clean it:

data_np = load_data_np[1:,:].copy()
data_np[:5,:]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2]])

In [10]:
# look at shape
data_np.shape

(150, 4)

#Task 2

Convert the remaining columns to a 2D array (or make sure that it is already a 2D array)

In [11]:
# looking on dimension

print(f"number of dimension is: {data_np.ndim}")

number of dimension is: 2


#Task 3

Calculate mean, median, standard deviation for the 1st column

In [12]:
#calculating mean for 1st column:

print(f"mean of 1st column: {data_np[:,1].mean()}")

#calculating median for 1st column:

# print(f"median of 1st column: {data_np[:,1].median()}")
# got 'numpy.ndarray' object has no attribute 'median'

#so another way:
print(f"median of 1st column: {np.median(data_np[:,1])}")

#calculating standart deviation of 1st column:

print(f"stand deviation of 1st column: {data_np[:,1].std()}")

mean of 1st column: 3.0540000000000003
median of 1st column: 3.0
stand deviation of 1st column: 0.4321465800705435


#Task 4

Insert 20 values of np.nan at random positions in the array (using normal randomization, there may be overlapping positions, so find a solution that guarantees 20 unique positions)

## Solution 1
we can solve this task by generating rendom 20 values in range of leght data rows and mutate in in past

In [13]:
data_np.shape

(150, 4)

In [14]:
# generating random numbers
rng = np.random.default_rng(seed=42)

# generate by random.integers function:
# Return random integers from low  to high

random_numbers = rng.integers(0, 3, 20)
print(random_numbers)

[0 2 1 1 1 2 0 2 0 0 1 2 2 2 2 2 1 0 2 1]


In [15]:
#copying data to new variable

nan_array = data_np.copy()

In [16]:
# mutate random values to nan

nan_array[np.arange(20), random_numbers] = np.nan

In [17]:
#check and count nan by function np.unique:

values, counts = np.unique(nan_array, return_counts=True)

print(values)
print(counts)

[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9 nan]
[ 6 28  7  7  1  1  8  3  6 20 18 24 10  4 12  7  7  6  6 12  6 11  5  9
 14 10 27 11 12  8 12  8  3  3  6  4  6  4  5  3  7  9  6  7  9 10 14 15
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1 20]


In [18]:
nan_array.shape

(150, 4)

## Solution 2
And we can use random_numbers from previous task, and generate 20 numbers from data indicies

In [19]:
#copying data

test_data_np = data_np.copy()

In [20]:
#generating numbers from indicies

test_data_choice = rng.choice(test_data_np.shape[0], 20, replace=False, axis= 0)
print(test_data_choice)

[ 79  63 105  87  65  62  94  24   9 113 122  75  32 126  41  48  55  13
 128 124]


In [21]:
#mutate random numbers to nan

test_data_np[test_data_choice, random_numbers] = np.nan

In [22]:
#check out data
test_data_np

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [nan, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [nan, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, nan, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, nan, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [23]:
#get counts of each unique numbers where nan include

test_values, test_counts = np.unique(test_data_np, return_counts=True)

print(test_values)
print(test_counts)

[0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9 nan]
[ 6 28  7  7  1  1  8  4  7 19 20 24 11  6 12  6  7  6  6 11  6 11  5  9
 12 10 26 11 13  7 12  8  4  4  7  5  5  4  5  2  7  9  7  6  8 10 14 17
  6  3  8 10 10  9 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1 20]


# **Task 5**

Find the positions of the inserted np.nan values in the 1st column

In [24]:
#copying data to new variable

find_pos = test_data_np.copy()

In [25]:
#first column with nan values

first_col_nan = np.isnan(find_pos[:,0])

fst_col_nan_indicies = np.where(first_col_nan==True)

print(f" indices of nan in first column are: {fst_col_nan_indicies}")

 indices of nan in first column are: (array([  9,  13,  79,  94, 113]),)


#**Task 6**

Filter the array by the condition: values in the 3rd column > 1.5 and values in the 1st column < 5.0 (save to another variable)

In [26]:
# copying variable

filtered_data = test_data_np.copy()

In [27]:
#filter data regarding task
new_filter = filtered_data[(filtered_data[:, 3] > 1.5) & (filtered_data[:,1]<5.0)]
new_filter

array([[6.3, 3.3, 4.7, 1.6],
       [5.9, 3.2, 4.8, 1.8],
       [6.7, 3. , 5. , 1.7],
       [6. , 2.7, 5.1, 1.6],
       [6. , 3.4, 4.5, 1.6],
       [6.3, 3.3, 6. , 2.5],
       [5.8, 2.7, 5.1, 1.9],
       [7.1, 3. , 5.9, 2.1],
       [6.3, 2.9, 5.6, 1.8],
       [6.5, 3. , 5.8, 2.2],
       [4.9, 2.5, 4.5, 1.7],
       [7.3, 2.9, 6.3, 1.8],
       [6.7, 2.5, 5.8, 1.8],
       [7.2, 3.6, 6.1, 2.5],
       [6.5, 3.2, 5.1, 2. ],
       [6.4, 2.7, 5.3, 1.9],
       [6.8, 3. , 5.5, 2.1],
       [nan, 2.5, 5. , 2. ],
       [5.8, 2.8, 5.1, 2.4],
       [6.4, 3.2, 5.3, 2.3],
       [6.5, 3. , 5.5, 1.8],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 2.6, 6.9, 2.3],
       [6.9, 3.2, 5.7, 2.3],
       [5.6, 2.8, 4.9, 2. ],
       [6.3, 2.7, 4.9, 1.8],
       [7.2, 3.2, 6. , 1.8],
       [6.2, 2.8, nan, 1.8],
       [6.1, 3. , 4.9, 1.8],
       [6.4, 2.8, nan, 2.1],
       [7.2, 3. , 5.8, 1.6],
       [7.4, 2.8, 6.1, 1.9],
       [7.9, 3.8, 6.4, 2. ],
       [6.4, 2.8, 5.6, 2.2],
       [7.7, 3

#**Task 7**

Replace all np.nan values with 0

In [28]:
#copy data to new variable

replaced_data = new_filter.copy()

In [29]:
#check for nan before replacing values

np.unique(np.isnan(replaced_data))

array([False,  True])

In [30]:
# check for nan condition and replace it by 0 values

replaced_data = np.where(~np.isnan(replaced_data), replaced_data, 0)

#check for nan

np.unique(np.isnan(replaced_data))

array([False])

#**Task 8**

Count all unique values in the array and print them along with the number


In [31]:
# count all values

replaced_data_values, data_values_count = np.unique(replaced_data, return_counts=True)

# i'm iterate first 10 unique values just for better vision

for i, n in zip(replaced_data_values[:10], data_values_count[:10]):
  print(f"value {i} appear in data {n} times")



value 0.0 appear in data 3 times
value 1.6 appear in data 4 times
value 1.7 appear in data 2 times
value 1.8 appear in data 12 times
value 1.9 appear in data 5 times
value 2.0 appear in data 5 times
value 2.1 appear in data 4 times
value 2.2 appear in data 3 times
value 2.3 appear in data 8 times
value 2.4 appear in data 3 times


#Task 9
Split the array vertically into 2 equal parts (do not use absolute numbers, there should be two arrays of 4 columns each

In [32]:
#create copy
data_split = data_np.copy()

In [33]:
# Split an array into multiple sub-arrays as views into ary.
data_split = np.split(data_split, 2, axis=0)

print(data_split[0].shape)
print(data_split[1].shape)

(75, 4)
(75, 4)


#**Task 10**
Sort both arrays by the 1st column: 1st in ascending order, 2nd in descending order

In [34]:
sort_var = data_split.copy()

In [35]:
# sort 1st previous array by ascending

sort_ascend = data_split[0]
sort_descend = data_split[1]

In [36]:
#sorting descending by first column

x_sorted_desc = sort_descend[sort_descend[:, 0].argsort()[::-1]]
x_sorted_desc[:10, :]

array([[7.9, 3.8, 6.4, 2. ],
       [7.7, 2.8, 6.7, 2. ],
       [7.7, 2.6, 6.9, 2.3],
       [7.7, 3.8, 6.7, 2.2],
       [7.7, 3. , 6.1, 2.3],
       [7.6, 3. , 6.6, 2.1],
       [7.4, 2.8, 6.1, 1.9],
       [7.3, 2.9, 6.3, 1.8],
       [7.2, 3. , 5.8, 1.6],
       [7.2, 3.6, 6.1, 2.5]])

In [37]:
#sorting ascending by first column

x_sorted_ascend = sort_ascend[sort_ascend[:, 0].argsort()[::1]]
x_sorted_ascend[:10, :]

array([[4.3, 3. , 1.1, 0.1],
       [4.4, 2.9, 1.4, 0.2],
       [4.4, 3.2, 1.3, 0.2],
       [4.4, 3. , 1.3, 0.2],
       [4.5, 2.3, 1.3, 0.3],
       [4.6, 3.1, 1.5, 0.2],
       [4.6, 3.4, 1.4, 0.3],
       [4.6, 3.2, 1.4, 0.2],
       [4.6, 3.6, 1. , 0.2],
       [4.7, 3.2, 1.3, 0.2]])

#Task 11
Merge both arrays into one

In [38]:
# merge arrays with numpy.concatenate

merged_data = np.concatenate((x_sorted_ascend, x_sorted_desc), axis=0)

In [39]:
# check first 10 rows for ascending and last 10 rows for descending
print(f"first 10 rows: \n {merged_data[:10,:]} \n\n last 10 rows: \n {merged_data[-10:-1:1,:]}")

first 10 rows: 
 [[4.3 3.  1.1 0.1]
 [4.4 2.9 1.4 0.2]
 [4.4 3.2 1.3 0.2]
 [4.4 3.  1.3 0.2]
 [4.5 2.3 1.3 0.3]
 [4.6 3.1 1.5 0.2]
 [4.6 3.4 1.4 0.3]
 [4.6 3.2 1.4 0.2]
 [4.6 3.6 1.  0.2]
 [4.7 3.2 1.3 0.2]] 

 last 10 rows: 
 [[5.6 2.7 4.2 1.3]
 [5.6 2.8 4.9 2. ]
 [5.5 2.5 4.  1.3]
 [5.5 2.4 3.7 1. ]
 [5.5 2.4 3.8 1.1]
 [5.5 2.6 4.4 1.2]
 [5.4 3.  4.5 1.5]
 [5.1 2.5 3.  1.1]
 [5.  2.3 3.3 1. ]]


#**Task 12**
Find the most frequently repeated value in the array

In [40]:
#Count number of occurrences of each value in array of non-negative ints:

most_freq_value, count_value = np.unique(merged_data, return_counts=True)

In [41]:
# get index of the max value
index = np.argmax(count_value)

In [42]:
print(f"the most frequent value is: {most_freq_value[index]},\
                            \nit appear {np.max(count_value)} times")

the most frequent value is: 0.2,                            
it appear 28 times


In [43]:
# check it
print(f"values: {most_freq_value}")
print(f"counts: {count_value}")

values: [0.1 0.2 0.3 0.4 0.5 0.6 1.  1.1 1.2 1.3 1.4 1.5 1.6 1.7 1.8 1.9 2.  2.1
 2.2 2.3 2.4 2.5 2.6 2.7 2.8 2.9 3.  3.1 3.2 3.3 3.4 3.5 3.6 3.7 3.8 3.9
 4.  4.1 4.2 4.3 4.4 4.5 4.6 4.7 4.8 4.9 5.  5.1 5.2 5.3 5.4 5.5 5.6 5.7
 5.8 5.9 6.  6.1 6.2 6.3 6.4 6.5 6.6 6.7 6.8 6.9 7.  7.1 7.2 7.3 7.4 7.6
 7.7 7.9]
counts: [ 6 28  7  7  1  1  8  4  7 20 20 26 11  6 12  7  7  6  6 12  6 11  5  9
 14 10 27 12 13  8 12  8  4  4  7  5  6  4  5  3  8  9  7  7  9 11 14 17
  6  3  8 10 12 11 10  5  8  9  4 10  8  5  3 10  3  5  1  1  3  1  1  1
  4  1]


#**Task 13**
Write a function that multiplies all values in a column that are less than the average value in that column by 2 and divides the remaining values by 4

In [44]:
def remain_values(col):
    """Function compare and remain all values in column to avg value of that
    column if value lower it multiply on 2 if greater divides by 4.
    return data with changed column"""

    column  = np.where(col < np.mean(col), col*2, col/4)
    return column

#**Task 14**

Apply the resulting function to the 3rd column

In [45]:
test_data = data_np.copy()

In [46]:
test_data[:,2] = np.apply_along_axis(remain_values, axis=0, arr=test_data[:,2])

In [47]:
test_data

array([[5.1  , 3.5  , 2.8  , 0.2  ],
       [4.9  , 3.   , 2.8  , 0.2  ],
       [4.7  , 3.2  , 2.6  , 0.2  ],
       [4.6  , 3.1  , 3.   , 0.2  ],
       [5.   , 3.6  , 2.8  , 0.2  ],
       [5.4  , 3.9  , 3.4  , 0.4  ],
       [4.6  , 3.4  , 2.8  , 0.3  ],
       [5.   , 3.4  , 3.   , 0.2  ],
       [4.4  , 2.9  , 2.8  , 0.2  ],
       [4.9  , 3.1  , 3.   , 0.1  ],
       [5.4  , 3.7  , 3.   , 0.2  ],
       [4.8  , 3.4  , 3.2  , 0.2  ],
       [4.8  , 3.   , 2.8  , 0.1  ],
       [4.3  , 3.   , 2.2  , 0.1  ],
       [5.8  , 4.   , 2.4  , 0.2  ],
       [5.7  , 4.4  , 3.   , 0.4  ],
       [5.4  , 3.9  , 2.6  , 0.4  ],
       [5.1  , 3.5  , 2.8  , 0.3  ],
       [5.7  , 3.8  , 3.4  , 0.3  ],
       [5.1  , 3.8  , 3.   , 0.3  ],
       [5.4  , 3.4  , 3.4  , 0.2  ],
       [5.1  , 3.7  , 3.   , 0.4  ],
       [4.6  , 3.6  , 2.   , 0.2  ],
       [5.1  , 3.3  , 3.4  , 0.5  ],
       [4.8  , 3.4  , 3.8  , 0.2  ],
       [5.   , 3.   , 3.2  , 0.2  ],
       [5.   , 3.4  , 3.2  , 0.4  ],
 